datamodule:
  length_sec: 4
  batch_size: 16

model: "dcctn"        # new LightningModule wrapping Network.DCCTN
model_params:
  learning_rate: 1.0e-4
  # change this back
  weight_decay: 1.0e-4
  betas: [0.5, 0.999]
  stft_loss_config:
    fft_size: 256
    hop_size: 128
    win_length: 256
    scale_invariance: false
    w_sc: 1.0
    weight: 1.0
  # stft_loss_config:
  #   kind: "multi"
  #   fft_sizes: [256, 512, 1024]
  #   hop_sizes: [50, 64, 75]
  #   win_lengths: [200, 256, 300]
  #   w_log_mag: 1.0
  #   w_sc: 1.0 
  #   weight: 1.0
  # for random-resolution STFT
  # stft_loss_config:
  #   kind: "random"
  #   resolutions: 3          # matches the `resolutions` arg
  #   min_fft_size: 256
  #   max_fft_size: 1024      # keep this ≤32 000 for 4 s @ 8 kHz
  #   min_hop_size: 0.25      # proportion of window; tweak as needed
  #   max_hop_size: 0.5
  #   w_sc: 1.0
  #   w_log_mag: 1.0          # RandomResolutionSTFTLoss expects these weights
  #   w_lin_mag: 0.0
  #   weight: 1.0


trainer:
  fast_dev:
    max_epochs: 1
    limit_train_batches: 5
    limit_val_batches: 5
    gradient_clip_val: 0.5
    # strategy: "ddp_spawn"
    devices: [0]
    accelerator: "gpu"
  full:
    max_epochs: 8
    gradient_clip_val: 10.0
    accumulate_grad_batches: 8
    # strategy: "ddp"
    devices: [0]        # list for multi-GPU
    accelerator: "gpu"
  logging:
    use_wandb: true
    log_every_n_steps: 50
evaluate_test: false    # flip on to mimic DCCTN/test.py score dump
