
datamodule: 
  length_sec: 4
  batch_size: 8
  wavelet: "db1"
  level: 3
  tag: stack

model: "diffwave_v1"
model_params:
  learning_rate: 0.00001
  hop_samples: 256
  residual_layers: 64
  residual_channels: 128
  up_channels: 128
  dilation_cycle_length: 10
  n_bands: 4
