
datamodule: 
  length_sec: 4
  batch_size: 8
  wavelet: "db1"
  level: 3
  tag: all

model: "wnd_unet"
model_params:
  learning_rate: 0.001
  base_channels: 64
  lr_scheduler_patience: 3
  lr_scheduler_factor: 0.5
  weight_decay: 1.0e-4